# .github/workflows/hello-world.yml
name: hello-world             # Optional: The name shown in the GitHub Actions tab
on: [push]                    # The event that triggers the workflow

jobs:
  my-job:                     # ID for the job
    runs-on: ubuntu-latest    # The type of machine to run on
    steps:
      - name: my-step         # Optional: Name for this specific step
        run: echo "Hello World!"
